# Generated by Django 2.1.3 on 2018-12-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rankinguser_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankinguser',
            name='owner',
        ),
        migrations.AddField(
            model_name='rankinguser',
            name='renter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='renter', to='products.UserProfile'),
            preserve_default=False,
        ),
    ]
