# Generated by Django 2.1.2 on 2018-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181130_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='code_zip',
            field=models.IntegerField(default=1),
        ),
    ]
