# Generated by Django 2.1.2 on 2018-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_direction_code_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='symbol',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
